src/Entity/Currency.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CurrencyRepository")
 */
class Currency
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $valute_id;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $num_code;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $char_code;

    /**
     * @ORM\Column(type="integer")
     */
    private $nominal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="decimal", precision=7, scale=4)
     */
    private $value;

    /**
     * @ORM\Column(type="date")
     */
    private $dateofadded;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValuteId(): ?string
    {
        return $this->valute_id;
    }

    public function setValuteId(string $valute_id): self
    {
        $this->valute_id = $valute_id;

        return $this;
    }

    public function getNumCode(): ?string
    {
        return $this->num_code;
    }

    public function setNumCode(string $num_code): self
    {
        $this->num_code = $num_code;

        return $this;
    }

    public function getCharCode(): ?string
    {
        return $this->char_code;
    }

    public function setCharCode(string $char_code): self
    {
        $this->char_code = $char_code;

        return $this;
    }

    public function getNominal(): ?int
    {
        return $this->nominal;
    }

    public function setNominal(int $nominal): self
    {
        $this->nominal = $nominal;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getDateofadded(): ?\DateTimeInterface
    {
        return $this->dateofadded;
    }

    public function setDateofadded(\DateTimeInterface $dateofadded): self
    {
        $this->dateofadded = $dateofadded;

        return $this;
    }
}

src/Model/Currency/Form/CurrencyHandlerType.php
<?php


namespace App\Form;


use App\Handlers\CurrencyHandler;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Форма для добавление курса валют
 * @package App\Form
 */
class CurrencyHandlerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateofadded', DateType::class, ['label' => 'Дата'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CurrencyHandler::class,
        ]);
    }
}

src/Model/Currency/Form/CurrencyType.php
<?php

namespace App\Form;

use App\Entity\Currency;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CurrencyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateofadded')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Currency::class,
        ]);
    }
}

src/Controller/CurrencyController.php
<?php

namespace App\Controller;

use App\Entity\Currency;
use App\Form\CurrencyHandlerType;
use App\Form\CurrencyType;
use App\Handlers\CurrencyHandler;
use App\Model\Currency\Filter;
use App\Model\Currency\Graph;
use App\Repository\CurrencyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/currency")
 */
class CurrencyController extends AbstractController
{
    private const PER_PAGE = 30;

    /**
     * @Route("/", name="currency_index", methods={"GET"})
     */
    public function index(Request $request, CurrencyRepository $currencyRepository): Response
    {
        $filter = new Filter\Filter();
        $form = $this->createForm(Filter\Form::class, $filter);
        $form->handleRequest($request);

        $pagination = $currencyRepository->all(
            $filter,
            $request->query->getInt('page', 1),
            self::PER_PAGE
//            $request->query->get('sort', 'c.dateofadded'),
//            $request->query->get('direction', 'desc')
        );

        return $this->render('currency/index.html.twig', [
            'pagination' => $pagination,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/cron", name="currency_cron")
     */
    public function cron(Request $request, CurrencyRepository $currencyRepository): Response
    {
        $currencyHandler = new CurrencyHandler();
        $currencyHandler->setDateofadded(new \DateTime('now'));

        $entityManager = $this->getDoctrine()->getManager();
        $currencyHandler->getCbrData($currencyRepository, $entityManager);

        return new Response();
    }

    /**
     * @Route("/new", name="currency_new", methods={"GET","POST"})
     */
    public function new(Request $request, CurrencyRepository $currencyRepository): Response
    {
        $currencyHandler = new CurrencyHandler();
        $currencyHandler->setDateofadded(new \DateTime('now'));
        $form = $this->createForm(CurrencyHandlerType::class, $currencyHandler);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            if ($currencyHandler->getCbrData($currencyRepository, $entityManager)) {
                return $this->redirectToRoute('currency_index');
            } else {
                $this->addFlash('notice', 'Данные за эту дату есть.');
            }

        }

        return $this->render('currency/new.html.twig', [
            'currencyHandler' => $currencyHandler,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/graph", name="currency_graph", methods={"GET"})
     */
    public function graph(Request $request, CurrencyRepository $currencyRepository): Response
    {
        $values = [];
        $valute = '';
        $filter = new Graph\Filter();
        $form = $this->createForm(Graph\Form::class, $filter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $values = $currencyRepository->getGraph($filter->num_code, $filter->date_from, $filter->date_till);
            $choices = array_flip($form->get('num_code')->getConfig()->getOption('choices'));
            $valute = $choices[$form->get('num_code')->getData()];
        }

        return $this->render('currency/graph.html.twig', [
            'form' => $form->createView(),
            'values' => $values,
            'valute' => $valute,
            'filter' => $filter
        ]);
    }

    /**
     * @Route("/json", name="currency_json", methods={"GET"})
     */
    public function sendJson(Request $request, CurrencyRepository $currencyRepository): Response
    {
        $filter = new Graph\Filter();
        $filter->num_code = $request->get('num_code');
        $filter->date_from = $request->get('date_from');
        $filter->date_till = $request->get('date_till');

        $values = [];
        $arr = $currencyRepository->period($filter);
        if ($arr) {
            foreach ($arr as $currency) {
                $values[] = [
                    'date' => $currency->getDateofadded()->format('Y-m-d'),
                    'value' => $currency->getValue() * $currency->getNominal()
                ];
            }
        }

        $response = new Response(json_encode($values));
        $response->headers->set('Content-Type', 'application/json');

        return $response;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}{% endblock %}
</head>
<body>
<div class="container">
    {% block body %}{% endblock %}
</div>
{% block javascripts %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/currency/_form.html.twig
{% for message in app.flashes('notice') %}
    <div class="flash-notice">
        {{ message }}
    </div>
{% endfor %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-secondary">{{ button_label|default('Получить данные валют') }}</button>
{{ form_end(form) }}

templates/currency/graph.html.twig
{% extends 'base.html.twig' %}

{% block title %}График изменения валюты{% endblock %}

{% block body %}
    <h1>График изменения валюты</h1>

    {{ form_start(form) }}
    <div class="row py-2">
        <div class="col">{{ form_widget(form.num_code) }}</div>
        <div class="col">{{ form_widget(form.date_from) }}</div>
        <div class="col">{{ form_widget(form.date_till) }}</div>
        <div class="col">
            <button type="submit" class="btn btn-primary">Показать</button>
        </div>
    </div>
    {{ form_end(form) }}
    <a href="{{ path('currency_index') }}">back to list</a>

    {% if values %}
        <div>
            <canvas
                    id="valuteChart"
                    class="my-3"
            >
            </canvas>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
            <script>
                var ctx = document.getElementById('valuteChart');
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: [
                            {% for currency in values %}
                            '{{ currency.dateofadded|date('Y-m-d') }}',
                            {% endfor %}
                        ],
                        datasets: [{
                            label: '{{ valute }}',
                            data: [
                                {% for currency in values %}
                                '{{ currency.value * currency.nominal }}',
                                {% endfor %}
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                }
                            }]
                        }
                    }
                });
            </script>
        </div>

        <a class="btn btn-primary" href="{{ path('currency_json', {num_code: filter.num_code, date_from: filter.date_from|date('Y-m-d'), date_till: filter.date_till|date('Y-m-d')}) }}">JSON</a>
    {% endif %}
{% endblock %}

templates/currency/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Currency index{% endblock %}

{% block body %}
    <h1>Currency index</h1>
    {{ form_start(form) }}
    <div class="row py-2">
        <div class="col">{{ form_widget(form.num_code) }}</div>
        <div class="col">{{ form_widget(form.dateofadded) }}</div>
        <div class="col"><button type="submit" class="btn btn-primary">Фильтровать</button></div>
    </div>
    <a href="{{ path('currency_graph') }}">График</a>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Num code</th>
            <th>{{ knp_pagination_sortable(pagination, 'Char code', 'c.char_code') }}</th>
            <th>Номинал</th>
            <th>Наименование</th>
            <th>Курс</th>
            <th>{{ knp_pagination_sortable(pagination, 'Дата', 'c.dateofadded') }}</th>
        </tr>
        </thead>
        <tbody>
        {% for currency in pagination %}
            <tr>
                <td>{{ currency.valuteId }}</td>
                <td>{{ currency.numCode }}</td>
                <td>{{ currency.charCode }}</td>
                <td>{{ currency.nominal }}</td>
                <td>{{ currency.name }}</td>
                <td>{{ currency.value }}</td>
                <td>{{ currency.dateofadded ? currency.dateofadded|date('Y-m-d') : '' }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {{ form_end(form) }}
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
    <a href="{{ path('currency_new') }}">Create new</a>
{% endblock %}

templates/currency/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Currency{% endblock %}

{% block body %}
    <h1>Create new Currency</h1>

    {{ include('currency/_form.html.twig') }}

    <a href="{{ path('currency_index') }}">back to list</a>
{% endblock %}